const beats=window.BEATS;const deck=document.querySelector('#deck');let current=0;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const diagrams={friction:['Request','Follow-up','Missing context'],diagnose:['INPUT / What arrives?','DECISION / Who decides?','HANDOFF / What moves?'],design:['Clear starting point','Explicit rule','Visible exception path'],example:['01 / Capture','02 / Route + review','03 / Resolve'],safeguards:['Routine decision','Human review','Recover + record'],media:['Brief + beats','Footage + precise diagrams','Editable composition']};
function visual(b){if(b.video)return `<figure class="media-frame"><video controls playsinline preload="metadata" aria-label="Illustrative locally generated video for ${esc(b.eyebrow)}" src="${esc(b.video)}"></video><div class="media-fallback"><span class="diagram-label">Media validation</span><strong>Local generation trial</strong><p>The video could not load. Serve the complete showcase folder locally and check that its video files are present.</p></div><figcaption>LOCAL AI FOOTAGE · Illustrative atmosphere; not a real client or technical mechanism.</figcaption></figure><p class="media-note"></p>`;
if(b.id==='next')return `<div class="diagram"><span class="diagram-label">A practical starting point</span><div class="big-quote">Diagnose.<br>Design.<br><em>Build.</em></div><p class="sub">Systems consulting for leaders who execute.</p><a href="https://www.develotype.com/" target="_blank" rel="noopener">Explore Develotype ↗</a></div>`;
return `<div class="diagram"><div class="diagram-label">${b.id==='example'?'Illustrative request flow':'A working model'}</div>${(diagrams[b.id]||b.items).map((x,i)=>`${i?'<div class="connector"></div>':''}<div class="node ${i===1?'accent':''}">${esc(x)}<small>${String(i+1).padStart(2,'0')}</small></div>`).join('')}<div class="sub">${b.id==='safeguards'?'Uncertainty returns to a person with context.':b.id==='friction'?'The friction often lives between the tools.':'Exact relationships stay editable.'}</div></div>`;}
beats.forEach((b,i)=>{const s=document.createElement('section');s.className='beat';s.id='beat-'+b.id;s.setAttribute('aria-label',`${i+1}. ${b.title.replace('\n',' ')}`);s.innerHTML=`<p class="eyebrow">${esc(b.eyebrow)}</p><div class="layout"><div><h2 tabindex="-1">${esc(b.title)}</h2><p class="intro">${esc(b.body)}</p><ul class="points">${b.items.map((x,j)=>`<li><span>${String(j+1).padStart(2,'0')}</span>${esc(x)}</li>`).join('')}</ul></div><div class="visual">${visual(b)}<div class="source">${b.evidence.startsWith('https')?`Brand / positioning: <a href="${esc(b.evidence)}" target="_blank" rel="noopener">develotype.com</a>. Demo interpretation; not approved sales copy.`:esc(b.evidence)}</div></div></div>`;deck.append(s)});
document.querySelectorAll('video').forEach(v=>{const fallback=v.parentElement.querySelector('.media-fallback');v.addEventListener('loadedmetadata',()=>{fallback.hidden=true});v.addEventListener('error',()=>{fallback.hidden=false});});
function show(index,focus=false){current=Math.max(0,Math.min(beats.length-1,index));document.querySelectorAll('.beat').forEach((s,i)=>{s.classList.toggle('active',i===current);if(i!==current)s.querySelectorAll('video').forEach(v=>v.pause())});document.querySelector('#counter').textContent=`${String(current+1).padStart(2,'0')} / ${beats.length}`;document.querySelector('#chapter').textContent=beats[current].eyebrow;document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===beats.length-1;document.querySelector('#progress').style.width=`${(current+1)/beats.length*100}%`;document.querySelector('#notes').innerHTML=`<div class="label">PRESENTER NOTES · ~38 SECONDS</div><p>${esc(beats[current].notes)}</p><a href="static.html">Open static leave-behind ↗</a>`;if(focus)document.querySelector('.beat.active h2').focus({preventScroll:true});}
function go(i){if(i>=0&&i<beats.length){location.hash=beats[i].id;show(i,true);window.scrollTo({top:0,behavior:'instant'})}}document.querySelector('#prev').onclick=()=>go(current-1);document.querySelector('#next').onclick=()=>go(current+1);document.querySelector('#notes-toggle').onclick=e=>{const n=document.querySelector('#notes');n.hidden=!n.hidden;e.currentTarget.setAttribute('aria-expanded',String(!n.hidden));};document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.target.closest('button,a,input,textarea,select,video,[contenteditable]'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(current+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(current-1)}if(e.key==='Home')go(0);if(e.key==='End')go(beats.length-1)});window.addEventListener('hashchange',()=>{const i=beats.findIndex(b=>b.id===location.hash.slice(1));show(i<0?0:i)});show(Math.max(0,beats.findIndex(b=>b.id===location.hash.slice(1))));
